import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserratnter = Montserrat({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Skypro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta httpe-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={montserratnter.className}>{children}</body>
    </html>
  );
}
